
TOFOLLI = "toffoli"
CTRLX = "ctrlx"
X = "X"
Y = "Y"
Z = "Z"
U = "U"
ROTATION_X = "r_x"
ROTATION_Y = "r_y"
ROTATION_Z = "r_z"
H = "H"
SQRT_X = "sqrt_x"
MEASURE = "measure"
PHASE_SCALE = "phase_scale"
PHASE_KICK = "phase_kick"
C_PHASE_KICK = 'cphase'
INV_C_PHASE_KICK = "inv_cphase"