
KET_0 = "../Images/Circuit/ket_0.png"
KET_1 = "../Images/Circuit/ket_1.png"

GATE_SIZE = 32
GATE_H_SPACE = 3
GRID_OFFSET = 2

MAX_ROWS = 15
MAX_COLUMNS = 300

ARGAND_FIGURE_ID = 0
SCHODRINGER_EXPECTATIONS_FIGURE_ID = 1
HAMILTONIAN_PANEL_ID = 2
PSI_PANEL_ID = 3
QUANTUM_WALK_FIGURE_ID = 4
INSPECTOR_MATRIX_FIGURE_ID=5