import pydoc

pydoc.help(quantum_instance)
quantum_instance.init_register(nqubits=5, value=1)
quantum_instance.X(step=2, target=0)
quantum_instance.Y(step=3, target=0)
quantum_instance.Z(step=4, target=0)
quantum_instance.r_x(step=5, target=0, angle=1.571)
quantum_instance.r_y(step=6, target=0, angle=1.571)
quantum_instance.H(step=7, target=0)
quantum_instance.sqrt_x(step=8, target=0)
quantum_instance.phase_kick(step=9, target=0, angle=1.571)
quantum_instance.phase_scale(step=10, target=0, angle=1.571)
quantum_instance.cphase(step=11, target=0, k=0)
quantum_instance.inv_cphase(step=12, target=0, k=0)
quantum_instance.U(step=13, target=0, matrix=[1.00+0.00j, 0.000+0.000j, 0.000+0.000j, 1.000+0.000j])
quantum_instance.X(step=15, target=0)
quantum_instance.X(step=16, target=1)
quantum_instance.X(step=17, target=2)
quantum_instance.X(step=18, target=0)
quantum_instance.X(step=19, target=1)
quantum_instance.X(step=20, target=2)
quantum_instance.X(step=21, target=0)
quantum_instance.X(step=22, target=1)
quantum_instance.X(step=23, target=2)
quantum_instance.X(step=24, target=0)
quantum_instance.X(step=25, target=1)
quantum_instance.X(step=26, target=2)
quantum_instance.X(step=27, target=0)
quantum_instance.X(step=28, target=1)
quantum_instance.X(step=29, target=2)
quantum_instance.H(step=35, target=0)
quantum_instance.H(step=37, target=1)
quantum_instance.H(step=40, target=2)
quantum_instance.H(step=44, target=3)
quantum_instance.H(step=49, target=4)
quantum_instance.controlledX(step=2, ctrls=[2], target=1)
quantum_instance.controlledY(step=3, ctrls=[2], target=1)
quantum_instance.controlledZ(step=4, ctrls=[2], target=1)
quantum_instance.controlledr_x(step=5, ctrls=[2], target=1, angle=0.524)
quantum_instance.controlledr_y(step=6, ctrls=[2], target=1, angle=0.524)
quantum_instance.controlledH(step=7, ctrls=[2], target=1)
quantum_instance.controlledsqrt_x(step=8, ctrls=[2], target=1)
quantum_instance.controlledphase_kick(step=9, ctrls=[2], target=1, angle=0.524)
quantum_instance.controlledphase_scale(step=10, ctrls=[2], target=1, angle=0.524)
quantum_instance.controlledcphase(step=11, ctrls=[2], target=1, k=1)
quantum_instance.controlledinv_cphase(step=12, ctrls=[2], target=1, k=1)
quantum_instance.controlledU(step=13, ctrls=[2], target=1, matrix=[0.00+0.00j, 1.000+0.000j, 1.000+0.000j, 0.000+0.000j])
quantum_instance.controlledX(step=31, ctrls=[1, 2], target=3)
quantum_instance.controlledX(step=32, ctrls=[1], target=2)
quantum_instance.controlledX(step=33, ctrls=[0, 2], target=3)
quantum_instance.controlledcphase(step=36, ctrls=[0], target=1, k=-1)
quantum_instance.controlledcphase(step=38, ctrls=[0], target=2, k=-2)
quantum_instance.controlledcphase(step=39, ctrls=[1], target=2, k=-2)
quantum_instance.controlledcphase(step=41, ctrls=[0], target=3, k=-3)
quantum_instance.controlledcphase(step=42, ctrls=[1], target=3, k=-3)
quantum_instance.controlledcphase(step=43, ctrls=[2], target=3, k=-3)
quantum_instance.controlledcphase(step=45, ctrls=[0], target=4, k=-4)
quantum_instance.controlledcphase(step=46, ctrls=[1], target=4, k=-4)
quantum_instance.controlledcphase(step=47, ctrls=[2], target=4, k=-4)
quantum_instance.controlledcphase(step=48, ctrls=[3], target=4, k=-4)
quantum_instance.measure(step=14, target=0)
quantum_instance.measure(step=14, target=1)
quantum_instance.measure(step=14, target=2)
